# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

g <- function(n) {
    .Call(`_causl_g`, n)
}

dGcop <- function(x, sigma, logd = FALSE) {
    .Call(`_causl_dGcop`, x, sigma, logd)
}

dGcop_sig <- function(x, sigma, logd = FALSE) {
    .Call(`_causl_dGcop_sig`, x, sigma, logd)
}

dGDcop2 <- function(x, sigma, trunc, logd = FALSE) {
    .Call(`_causl_dGDcop2`, x, sigma, trunc, logd)
}

dGDcop <- function(x, sigma, trunc, logd = FALSE) {
    .Call(`_causl_dGDcop`, x, sigma, trunc, logd)
}

dGDcop_sig <- function(x, sigma, trunc, logd = FALSE) {
    .Call(`_causl_dGDcop_sig`, x, sigma, trunc, logd)
}

dGDcop2_sig <- function(x, sigma, eta, q, logd = FALSE) {
    .Call(`_causl_dGDcop2_sig`, x, sigma, eta, q, logd)
}

